version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3500:3500
    volumes:
      - ./:/app
      - /app/node_modules
    command: bash start.sh



